### ISSUE TITLE
v2.0 ship list

### ISSUE THREAD

**Issue by arocks** [arocks/edge#10]
All these changes are present in the https://github.com/arocks/edge/tree/accounts2profiles feature branch

# Models
- User model customized (thanks to **authtools**)
  - Use emails as the primary key. username will not be required.
  - Use full names instead of first name and last name.

# Profile :sparkles:
- Profiles app: Each user will have a corresponding profile https://github.com/arocks/edge/issues/2 . The default profile details are:
  - Profile Picture: any image can be uploaded. By default a grey head appears.
  - Bio: a short writeup
  - Email Verification status: whether the user clicked on the link in the verification email. Refer Auth.
- Show profile: A view to show the user's profile in an attractive page. It has a permalink which can be shared without revealing user's email or database primary key using UUID.
- Edit profile: A combined view with user editable details and profile editable details in a single view.

# Appearance
- Themed: ships with Bootswatch [Lumen](http://bootswatch.com/lumen/) theme by default
- Navbar See Thru: Cover image can be seen through the navbar. Upon scrolling the navbar becomes opaque.
- Crispy forms: Every form has been styled to look Bootstrap-native using crispy forms.
- Profile Pic on Navbar: appears next to user's full name
- Light Navbar: Dark bar was looking too Bootstrap-ish
- Upgraded to Bootstrap v3.3.2 https://github.com/arocks/edge/issues/8

# Admin
- Switch to site: A button on the admin navbar takes you to the home page quickly
- Profiles inlined to User: There is no separate admin interface for profiles making it cleaner and less confusing.
- Permalink: Unique link to every user's profile shown in user list view

# Python 2.7 Support :boom:
- Project Template now supports Python 2.7. The super syntax was applied and pathlib library dependency was removed. https://github.com/arocks/edge/issues/4

# Environment specific Settings and Requirements files
- Pip Requirement files are now split into dev, prod etc
- Settings files have been split into dev, prod etc. https://github.com/arocks/edge/issues/3

# Authentication Workflows
- Signup: fill a simple signup form and it will log you in automatically. There is no email verification step.
- Login: login form takes the email address and password. Forget password and Remember me features are also implemented.
- Logout: takes you back to home page
- Forgot Password: Sends a password reset mail. Clicking on the password reset prompts for a new password (twice). Then you are automatically logged in.
- Change Password: The edit profile page has a password change link.

All these are class-based views wrapped around standard Django auth functions for easy customization.

# Other Changes
- URL names are namespaced to respective apps: Refer to "accounts:login" rather than "login". The "home" and "about" urls are not namespaced.
- Test cases now check only if the pages return a success code rather than the exact view function.
- Added a console backend for email handling while development.
- Login and Signup form removed from Home page: Most modern websites take users to seperate pages for login and signup. As Login forms added more features it gets clunky to fit in the navbar.
- Alerts moved to below navbar.

**Comment by ParvJain** [comment]
massive update. Kudos!

**Comment by arocks** [comment]
Thanks!

**Comment by Picatek** [comment]
I get: ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
when I run:
python manage.py migrate
I tryed both:
1.
 SECRET_KEY = 'of6xfs&$nt*-aaf2$vyx2$u_4za5*!*5f-b4aqg*y_w)@=t_hf'
int settings/base.py
2. 
export SECRET_KEY = 'of6xfs&$nt*-aaf2$vyx2$u_4za5*!*5f-b4aqg*y_w)@=t_hf'
but still get the same error

**Comment by arocks** [comment]
Hi @Picatek , could you share a zipped version of your project? I have not come across this issue before. Thanks!

**Comment by Picatek** [comment]
Hi Arun
Thanks for answering me.
Zipping the project is 114MB file. Not sure may mail can send it. I can
send you the stack trace to begin with.
Let me know if it make sense to you:


ico@UbuntuVB:~/projects/baseprj/logsiteprj/src$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    print(os.environ(DEFAULTS_PATH))
NameError: name 'DEFAULTS_PATH' is not defined
ico@UbuntuVB:~/projects/baseprj/logsiteprj/src$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File
"/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py",
line 385, in execute_from_command_line
    utility.execute()
  File
"/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py",
line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File
"/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py",
line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File
"/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py",
line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in
_call_with_frames_removed
  File
"/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py",
line 15, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File
"/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py",
line 5, in <module>
    from .loader import MigrationLoader
  File
"/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py",
line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File
"/usr/local/lib/python3.4/dist-packages/django/db/migrations/recorder.py",
line 9, in <module>
    class MigrationRecorder(object):
  File
"/usr/local/lib/python3.4/dist-packages/django/db/migrations/recorder.py",
line 23, in MigrationRecorder
    class Migration(models.Model):
  File
"/usr/local/lib/python3.4/dist-packages/django/db/migrations/recorder.py",
line 24, in Migration
    app = models.CharField(max_length=255)
  File
"/usr/local/lib/python3.4/dist-packages/django/db/models/fields/__init__.py",
line 1012, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File
"/usr/local/lib/python3.4/dist-packages/django/db/models/fields/__init__.py",
line 146, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py",
line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py",
line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py",
line 115, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must
not be empty.
ico@UbuntuVB:~/projects/baseprj/logsiteprj/src$


Best Regards
Itamar Cohen
Picatek
Ahornvej 27
DK-7700 Thisted
Denmark
www.picatek.dk
it@picatek.dk
T: +45 97 91 07 82
M:+45 29 89 07 82

**Comment by ParvJain** [comment]
just asking for a small advice,

i want to get the input of user's bio while signing up, what changes can i make to the code.

**Comment by arocks** [comment]
@Picatek you seem to have done a fair bit of customization. Could you try with a fresh deployment of edge? If you could raise an issue and detail how to reproduce the error, then it would be easier. Please do mention the details of your setup like OS, python version, etc. Thanks!

**Comment by arocks** [comment]
@ParvJain Just extend the signup form and its `save()` method.

**Comment by Picatek** [comment]
Thanks Arun
I installed it on a fresh VM without an issue so it was probably something
in my setup. Never mind





Best Regards
Itamar Cohen
Picatek
Ahornvej 27
DK-7700 Thisted
Denmark
www.picatek.dk
it@picatek.dk
T: +45 97 91 07 82
M:+45 29 89 07 82

**Comment by Picatek** [comment]
Hi
in your   LoginForm.confirm_login_allowed (self,user) you have the following line:
 self.request.session.set_expiry(expiry)

But self has no request object

**Comment by arocks** [comment]
@Picatek Did you get an error? The view is derived from FormView, so it should be set.

**Comment by Picatek** [comment]
Yes! If  when you login and check the Remember me checkbox you get:
Exception Value:	
'NoneType' object has no attribute 'session'
Exception Location:	/home/ico/projects/logsiteprj/logterm/src/accounts/forms.py in confirm_login_allowed, line 39
Python Executable:	/home/ico/projects/logsiteprj/venv/bin/python3

By the way if I want to go back to the old admin looks , how do I do it
The reason is that my models has  lots of details and the bootstrap  wastes lots of scree real estate.
Or do you have better idea  how to make it more compact

**Comment by arocks** [comment]
@Picatek regarding the looks, you have two options. You can add an if condition to the `home.html` to show the jumbotron only if the user is not logged in (`if not user.is_authenticated`). Or you can reduce the height of the jumbotron, say `.corporate-jumbo { height: 50%; }` in `main.css`
