### ISSUE TITLE
profile model

### ISSUE THREAD

**Issue by pajooh** [arocks/edge#2]
adding a model in account with one-to-one relation to User model to be used as user profile, and letting profile filled in registration form is very needed :)

keep up the good work!

**Comment by arocks** [comment]
Thanks for requesting this. I plan to implement this in a general manner soon. Keep watching :)

**Comment by arocks** [comment]
Hi @pajooh 

Please have a look at the pull request https://github.com/arocks/edge/pull/7 for a Profile model implementation. It doesn't have the registration form yet.

Your comments would be valuable.

**Comment by arocks** [comment]
Added profile model in Edge v2.0
