### ISSUE TITLE
local env

### ISSUE THREAD

**Issue by lerrua** [arocks/edge#24]
Hello Arun,

Maybe the `local.env` file be added in `.gitignore` and the project can be generated: `local.env.sample` file and copied to `local.env` for deploy and local settings.

What do you guys think?

**Comment by arocks** [comment]
Wouldn't that be an additional step while setting up dev then?

**Comment by arocks** [comment]
Thanks for this suggestion. The idea has been implemented in https://github.com/arocks/edge/tree/1_8

**Comment by lerrua** [comment]
Nice! ;)

**Comment by arocks** [comment]
Merged to master
