### ISSUE TITLE
django-flat-admin proposal

### ISSUE THREAD

**Issue by lerrua** [arocks/edge#25]
H guys,

What do you think changing the admin-bootstrapped for django-flat-theme[1]?

1 - https://github.com/elky/django-flat-theme

**Comment by arocks** [comment]
I would like to welcome everybody's opinion on this one as it is also an aesthetic preference. Currently, the biggest plus of the admin interface is that it looks consistent to the main site by reusing the logo and bootstrap theme. I am also aware of another attempt by Django developers to modernize the admin itself.

**Comment by arocks** [comment]
@lerrua I believe this is getting integrated upstream into Django itself. See https://groups.google.com/forum/#!topic/django-developers/HJAikaEBqJ4

Once merged, we can take a call on whether the admin reskinning in Edge needs to continue. Closing this issue for now.
