### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by sebastian-code** [arocks/edge#29]
The first thing to say, is to start with a big thank you, I don't know if you receive enough appreciation for this work, but is a great template, and perhaps you deserve more than you get.

After this introduction, the only thing I think the template lacks right now is a good integration with the internationalization core of the Django Framework. As you may see, my mother language is not english, and it implies a lot of unnecessary work to do going to translations, not just within the template, but also from the derivatives, is there a way to integrate the whole templating system with the internationalization underlying side of the framework?

Obviously I don't know if something like that there is a way to do it, but if there is one, perhaps is a "nice to have" feature.

**Comment by arocks** [comment]
Thank a lot, @sebastian-code ! You have an excellent point. Sooner or later most websites will need to address internationalization. In the case of Django templates in Edge, a number of hooks need to be added to make it easy to support this. I think it is definitely doable but requires a lot of diligence.

I shall definitely keep this in mind while working on future versions. I would be more than happy if someone volunteers :smiley:

**Comment by sebastian-code** [comment]
Hi @arocks and thanks for answering, I would say than I can be a volunteer, but I lack every single capability to help, I mean the knowledge, but I can learn; is there a point were I can start?

I think than the Mezzanine project has overcome the same thing, so perhaps there is something to take from them.
