### ISSUE TITLE
Add steps to Quickstart guide?

### ISSUE THREAD

**Issue by usonianhorizon** [arocks/edge#32]
Just installed on Ubuntu 14.04.

For installing virtual environment using venv, I ended up using the guides at:

[CodeGhar](https://codeghar.wordpress.com/2013/09/27/virtualenv-with-python-3-using-venv/)

and

[Chapmandu](http://chapmandu.com/2014/10/14/install-python-3-4-django-1-7-on-ubuntu-14-04-in-a-venv-virtual-environment/)

After the step:
```
$ pip install -r requirements.txt 
```

I think that there should be explicit reference to copying local.sample.env to local.env as without this step an exception gets raised about the SECRET_KEY, which can be mysterious.

Thanks.

**Comment by usonianhorizon** [comment]
Oops, I just noticed the extra step to copy local.sample.env is listed at GitHub.  However, this has not yet been updated on [readthedocs.org](http://django-edge.readthedocs.org/en/latest/#quick-start) which is where I was getting the instructions.  So perhaps just a mirrored update there?

Regards.

**Comment by arocks** [comment]
Thanks for pointing this out. I have updated the documentation with this step and an FAQ entry.

**Comment by tigerneil** [comment]
thanks a lot @usonianhorizon
