### ISSUE TITLE
Duplicate </ul> on lines 77, 78

### ISSUE THREAD

**Issue by usonianhorizon** [arocks/edge#34]
In Firefox HTML preview, line 78 is throwing up a syntax error with a duplicated `</ul>` just above the `</div><!--/.nav-collapse -->` line.

Regards.

**Comment by arocks** [comment]
Marking this for a proper HTML check.

**Comment by arocks** [comment]
Thanks to @sanjeev29 for validating all the HTML files and ensuring that they passed.
