### ISSUE TITLE
Isn't admin-bootstrapped going to break lots of 3rd party admin extensions?

### ISSUE THREAD

**Issue by andybak** [arocks/edge#38]
Anything that replaces templates is problematic with regards to compatibility.

(The flat theme that is likely to be included in Django 1.9 is CSS only: https://github.com/elky/django-flat-theme )

**Comment by arocks** [comment]
I agree that the new admin looks a lot better. But in edge, the admin theme closely matches the theme of the main site, which reduces the jarring effect while switching to admin and back.

Regarding third party tools, `django_admin_bootstrapped` uses the documented means of extending the admin like widgets and template tages, so it should play well with other third party admin extensions.
