### ISSUE TITLE
Adapted for python27

### ISSUE THREAD

**Issue by dpeinado** [arocks/edge#4]
Hi, very nice setup: simple but powerful. Without a lot of packages, but with the basics needed. Great Job!!.
Nevertheless, I’m still using Python27, so I’ve forked your edge and readapted for Python27. I can share this with you, but I do not know how can you offer both.

**Comment by arocks** [comment]
Hi dpeinado,

I was reading your fork here: https://github.com/dpeinado/edge/

Great work! Do you intend to maintain it? I can link to you from my docs if you don't mind.

**Comment by pmav99** [comment]
@dpeinado 
An alternative that would allow to have a single repo would be to have the python2 code on a different branch (e.g. a branch named `python2`). The ultimate question is whether or not @arocks wants to take over the maintainance of the python2 branch.

**Comment by arocks** [comment]
@pmav99 I don't mind maintaining a python 2 branch. However, I am looking the option of having a common codebase for both Python 2 and 3. Pathlib library has been backported. The remaining changes listed by @dpeinado are primarily about changing the `super()` syntax. It might be doable.

**Comment by arocks** [comment]
Edge v2.0 now works with Python 2.7!
