### ISSUE TITLE
HTML in profiles/templates/profiles/show_profile.html missing </div>

### ISSUE THREAD

**Issue by cjrh** [arocks/edge#46]
There is a closing `</div>` missing in `show_profiles.html`: 

![needonemorediv](https://cloud.githubusercontent.com/assets/480395/9979695/32c0a776-5fbc-11e5-8fc3-42222a63d584.png)

This isn't immediately obvious until you try a full-width footer ;)

**Comment by arocks** [comment]
Thanks!
