### ISSUE TITLE
Django 1.8 support?

### ISSUE THREAD

**Issue by gamesbook** [arocks/edge#62]
Apologies if this is described somewhere; but I could not see if support is offered for the Django LTS version 1.8? 

If it is compatible, would it be possible to add a short note to the Quickstart Guide?

**Comment by arocks** [comment]
Yes the current code is compatible with Django 1.8. I need to update the docs soon 😄

**Comment by gamesbook** [comment]
Thanks.

**Comment by achillis1** [comment]
Is it compatible with 1.10.2?
