### ISSUE TITLE
add additional crucial information in registration

### ISSUE THREAD

**Issue by tigerneil** [arocks/edge#72]
#I am using edge to develop my website. Now I plan to add additional attributes (special card number + activation password) in registration stage. 

I check the following 
https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html

And I think the forth choice is suitable for me.
But I don't know how to adapt `authtools` to achieve this goal.
Any comments?

**Comment by arocks** [comment]
Hi @tigerneil 

Edge is designed specially to extend the user model with additional attributes. In the blog post you've mentioned, option 2 has been already implemented. I suggest you to look at the `profiles` app. 

For instance, the class `BaseProfile` in https://github.com/arocks/edge/blob/master/src/profiles/models.py can have more attributes. Then, you can modify `ProfileForm` in `forms.py`. Read other files in the same app and you will get the idea.

**Comment by tigerneil** [comment]
Thanks for the suggestion. I succeed to add a activation process. @arocks
