### ISSUE TITLE
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] ...>

### ISSUE THREAD

**Issue by umberto-jr** [arocks/edge#83]
I don't know how often people stumble on the error below, 
It happens after entering the start project command found in the instructions page:

`$ django-admin.py startproject --template=https://github.com/arocks/edge/archive/master.zip --extension=py,md,html,env my_proj`

`CommandError: couldn't download URL https://github.com/arocks/edge/archive/master.zip to master.zip: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
`

It took me a whole night trying workarounds without any success until today I tried something different: I manually downloaded the master.zip file and pointed it to the command:

`$ django-admin.py startproject --template=~/Desktop/edge-master.zip --extension=py,md,html,env my_proj
`

Hope it saves some beginners' time.

**Comment by ethereumcoder** [comment]
Oh, I've stumbled too that place

**Comment by arocks** [comment]
An SSL error occurs for some users especially on macOS. So explicit zip file download step is mentioned in the README.
