### ISSUE TITLE
Password reset fails

### ISSUE THREAD

**Issue by marquicus** [arocks/edge#85]
It throws:
django.urls.exceptions.NoReverseMatch: Reverse for 'password-reset-confirm' with keyword arguments '{'uidb64': 'MQ', 'token': '4y8-9acac778ce8d9c5f4616'}' not found. 1 pattern(s) tried: ['password\\-reset\\/(?P<uidb64>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\/(?P<token>[-a-zA-Z0-9_]+)\\/$']

**Comment by arocks** [comment]
Thanks to a pull request this is fixed!
