### ISSUE TITLE
issue with base.html and the "{% block container %}"

### ISSUE THREAD

**Issue by awinner1** [arocks/edge#89]
There seems to be a spacing issue in the base.html and any form that does not use the splash block. If the default splash block in the base.html is used, a part of the content block will be under the menu.

A good example of the issue is in the profiles\templates\profiles\edit_profil.html.

The header text:

  <h1 class="text-primary">Edit Profile</h1>
  <hr>

Is hidden under the menu, with the separator line just showing in my browsers.  I hacked a fix by putting a line in the default splash to take up the room so my forms all display correctly, but I just learning CCS so I'm sure there is a better way.

**Comment by arocks** [comment]
Thanks to @sanjeev29 's PR we have fixed this issue.

**Comment by awinner1** [comment]
Note: I believe the top part of the splash graphic is cut off by the nav bar, this is the ultimate issue.

**Comment by sanjeev29** [comment]
@awinner1 Are you still facing the same problem?
If yes,please share a screenshot of it

**Comment by sanjeev29** [comment]
Hey Arun!
Hope you're doing well :)
Can you please close issue #34 " Duplicate </ul> on lines 77, 78
<https://github.com/arocks/edge/issues/34> bug
<https://github.com/arocks/edge/issues?q=is%3Aissue+is%3Aopen+label%3Abug>"
as it is fixed in #93 " Make template HTML valid
<https://github.com/arocks/edge/pull/93>"
Thank you!

**Comment by arocks** [comment]
Hi @sanjeev29 I've marked #34 as closed

Thanks @awinner1 for suggesting a fix. We recently made some changes and found all pages were not obscured at the top. Could you check from the latest master?

**Comment by sanjeev29** [comment]
Hey @arocks @awinner1 
I checked the latest master and the pages appeared properly.

**Comment by sanjeev29** [comment]
@arocks I just found this in one of the pull requests.This is the "edit_profile_fix" branch i had created to fix the top of the edit_profile.html page.Can you tell me why this occured?

![screenshot 12 _li](https://user-images.githubusercontent.com/35601924/51671699-8295a200-1fef-11e9-8889-b25835395c7f.jpg)

**Comment by awinner1** [comment]
Yes, still seeing it, **EXAMPLE** is the edit profile screen, notice the gray background goes under the nav bar.
![image](https://user-images.githubusercontent.com/7736870/51694852-8eb13d80-1fb6-11e9-89ab-b9dcdd9b489f.png)

Add my fix, slightly modified for this:
`    {% block splash %}
    
    <div class="container">
      <div class="row">
        <h1 class="text-primary">No Splash</h1>
      </div>
    </div>
    
    {% endblock splash %}
`


notice the difference with my fix ( if you look closely, you can see the descender of the lower case 'p' in "splash" showing just below the nav bar....

![image](https://user-images.githubusercontent.com/7736870/51695092-15feb100-1fb7-11e9-9ed4-86faa726edc4.png)

**Comment by awinner1** [comment]
Also as a side question, what is the best way to update an existing project from the repo. you really can't do an "start project again, the repo has all the start project stuff still in it. Best I've found is to redo the start project, then do a compare between the new and old.

**Comment by sanjeev29** [comment]
@awinner1 Oh yes,now i understood what you were trying to tell.Thanks for the fix!
So,about the side question.Did you mean updating your local master according to the repo master?

**Comment by sanjeev29** [comment]
@awinner1 If at all I fix the top of the page with your code,"No splash" is hiding behind the navbar in show profile page and edit profile page and also it appears in password change page too.So,wouldn't it be better to just pad the profile-head container from the navbar?

**Comment by sanjeev29** [comment]
I just added another div class 'main' for profile header and gave some top padding and left the block splash empty.Check this out
![screenshot 14](https://user-images.githubusercontent.com/35601924/51704129-3e7dbe00-203e-11e9-811d-74a70c0d3d27.png)
![screenshot 15](https://user-images.githubusercontent.com/35601924/51704141-42114500-203e-11e9-8a9e-714d3312e984.png)
![screenshot 16](https://user-images.githubusercontent.com/35601924/51704142-43db0880-203e-11e9-996a-da21cd55f78c.png)

**Comment by awinner1** [comment]
sanjeev29: Side question: yes how go about updating an existing project with new bug fixes , new code from the template. I have changes in several of the HTML files, some of the .py files, ... Best I've found is to do a folder compare to a local copy of the repo, but even that has issues if the changes are in the app part of the project.

**Comment by arocks** [comment]
Anthony,

Have you checked out https://github.com/arocks/edge-devtools ? It is the
best way to make changes to Edge especially the templates. But making
changes to an existing project you generated from Edge, is still manual.
