### ISSUE TITLE
No automatic logout on a password-change

### ISSUE THREAD

**Issue by vharsh** [arocks/edge#91]
/type bug
/environment development
/area backend

# Summary
- As per the on-screen instruction I should automatically get logged out on a password change.

# Expected workflow:
1.0. Setup the project with `Pipenv` using the instructions specified in the project README.
1.1. I created a super-user for Django using the cli-command
```bash
└─ $ ▶ python manage.py createsuperuser
Email address: harsh59v@gmail.com
Name: Harsh Vardhan
Password: 
Password (again): 
Superuser created successfully.
```
 1.2. I started the development server.
```bash
└─ $ ▶ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 19, 2019 - 07:00:46
Django version 2.1.3, using settings 'harsh_proj.settings.development'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

1.3. I logged in, and went to `http://127.0.0.1:8000/users/me/edit/` and clicked change-password
1.4. I used a different password(and the same old-password) and I got logged out.

# Actual behaviour
.
.
.
1.4. I am still logged in(even after multiple refreshes), clearly the problem lies in the backend.

**Comment by vharsh** [comment]
![ ](https://user-images.githubusercontent.com/9304050/51424662-010cd100-1bf7-11e9-8843-70594d80a5b8.png)

**Comment by arocks** [comment]
Thanks @vharsh for finding and fixing this. Extra points for a detailed and well-formatted issue report!
