### ISSUE TITLE
Calling signup.html from home.html

### ISSUE THREAD

**Issue by WaffleMongeringShit** [arocks/edge#99]
Hi, 

I'd like to put the sign up form on top of the banner in the main page. However if i call the form from home.html, the views.py can't find the forms (because it's in accounts app). e.g.

`django.template.base.VariableDoesNotExist: Failed lookup for key [form] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'view': <my_env.views.HomePage object at 0x7f0ed11cec88>}]`

Tried adding the following to the home.html but no good:

```
  {% if not user.is_authenticated %}
  {% include "signup.html" %}
  {% include "auth_base.html" %}
  {% block form %}
    {% crispy form %}
    <div class="form-message">
      <p>
        Already signed up? <a href="{% url 'accounts:login' %}">Log in</a>.
      </p>
    </div>
  {% endblock form %}
  {% endif %}
```

Any easy way to get around it?

Thanks in advance, this repo is golden

**Comment by WaffleMongeringShit** [comment]
I'm still stuck here. Tried [inclusion tags](https://stackoverflow.com/questions/20708802/crispy-form-variabledoesnotexist-on-django) but didn't work out. Can anyone please point me in the right direction?

**Comment by arocks** [comment]
Hi @WaffleMongeringShit 

Looks like your view is looking for a form instance which SignUpView class populates. Have you tried deriving HomePage from SignUpView? The homepage is just a TemplateView anyways.

**Comment by benonilearns** [comment]
Hi @arocks , thanks a lot for your input. I will try in a couple of hours and report back.

**Comment by WaffleMongeringShit** [comment]
Hi @arocks , thanks a lot for your input. I will try in a couple of hours and report back.

**Comment by WaffleMongeringShit** [comment]
Hi @arocks, i managed to get it work. Didn't try registration functions yet but i think it's ok now. I simple changed the main view.py to the following:

```
from accounts import forms
from django.views import generic

class HomePage(generic.CreateView):
    template_name = "home.html"
    form_class = forms.SignupForm

class AboutPage(generic.TemplateView):
    template_name = "about.html"
```

So HomePage wnet from generic.TemplateView to generic.CreateView and form_class variable is now defined. 

Thanks a lot.
